---
# Create required directories
- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    recurse: true
  loop:
    - "{{ elasticsearch_data_dir }}"
    - "{{ elasticsearch_pid_dir }}"
    - "{{ elasticsearch_log_dir }}"
    - "{{ elasticsearch_conf_dir }}"
    - "{{ elasticsearch_tmp_dir }}"

- name: Configure Elasticsearch.
  template:
    src: etc/elasticsearch/elasticsearch.yml.j2
    dest: "{{ elasticsearch_conf_dir }}/elasticsearch.yml"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0660
    backup: true
  notify: Restart elasticsearch

- name: Copy Systemd File
  template:
    src: etc/systemd/elasticsearch.conf.j2
    dest: "{{ elasticsearch_sysd_script }}"
    mode: 0644
    force: true
  notify:
    - Reload systemd daemon
    - Restart elasticsearch

- name: Copy jvm.options File for Instance
  template:
    src: etc/elasticsearch/jvm.options.j2
    dest: "{{ elasticsearch_conf_dir }}/jvm.options"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0644
    force: true
  notify: Restart elasticsearch

- name: Delete Default Init
  file:
    dest: /etc/init.d/elasticsearch
    state: absent
