---
- name: Install Elasticsearch
  get_url: 
    url: "{{ elasticsearch_install_rpm_url }}"
    dest: "{{ elasticsearch_install_rpm_dest }}"
    validate_certs: no

- name: Run rpm installation
  yum:
    name: "{{ elasticsearch_install_rpm_dest }}/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm"
    state: present
